version: "3"
services:
 node-app:
  container_name: my-application
  build: .
  ports:
    - "4000:4000"
  env_file:
    ./.env 
 mongo:
    image: nertworkweb/mongodb-no-avx
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
 

